// apps/example-react/src/panels/StoragePanel.tsx
import {
  useCid,
  useIsHost,
  usePreimage,
  useStorageAuthorization,
  useSubmitPreimage,
  useUpload,
} from "@use-truapi/react";
import { useState } from "react";
import { Card, HookRow } from "../ui";

export function StoragePanel() {
  const authorization = useStorageAuthorization();
  const upload = useUpload();
  const [lastCid, setLastCid] = useState<string | undefined>(undefined);
  const fetched = useCid(lastCid);
  const [draft, setDraft] = useState("");
  // Raw preimage path (host-only): submit bytes, read them back by key.
  const isHost = useIsHost();
  const submitPreimage = useSubmitPreimage();
  const preimage = usePreimage(submitPreimage.data, { enabled: isHost });

  const error = authorization.error ?? upload.error ?? fetched.error ?? submitPreimage.error;

  return (
    <Card title="Cloud storage" desc="CID-addressed storage on the Bulletin chain.">
      <HookRow hook="useStorageAuthorization">
        <span className="badge" data-testid="storage-authorization">
          {authorization.data
            ? authorization.data.authorized
              ? `quota: ${authorization.data.remainingTransactions} txns / ${authorization.data.remainingBytes} bytes`
              : "not authorized"
            : "checking quota…"}
        </span>
      </HookRow>
      <HookRow hook="useUpload">
        <input
          data-testid="upload-input"
          value={draft}
          placeholder="Bytes to store"
          onChange={(e) => setDraft(e.target.value)}
        />
        <button
          type="button"
          data-testid="upload-submit"
          disabled={upload.isPending || draft === ""}
          onClick={() =>
            void upload
              .upload(new TextEncoder().encode(draft))
              .then((result) => setLastCid(result.cid?.toString()))
              .catch(() => {})
          }
        >
          {upload.isPending ? "Uploading…" : "Upload"}
        </button>
      </HookRow>
      <HookRow hook="useCid">
        {lastCid ? (
          <span className="muted">
            CID <code data-testid="upload-cid">{lastCid}</code> reads back:{" "}
            <span data-testid="cid-content">
              {fetched.data ? new TextDecoder().decode(fetched.data) : "fetching…"}
            </span>
          </span>
        ) : (
          <span className="muted">upload something to read it back by CID</span>
        )}
      </HookRow>
      <HookRow hook={["useSubmitPreimage", "usePreimage"]}>
        {isHost ? (
          <>
            <button
              type="button"
              data-testid="preimage-submit"
              disabled={submitPreimage.isPending || draft === ""}
              onClick={() =>
                void submitPreimage.submit(new TextEncoder().encode(draft)).catch(() => {})
              }
            >
              {submitPreimage.isPending ? "Submitting…" : "Submit as preimage"}
            </button>
            {submitPreimage.data && (
              <span className="muted">
                key <code data-testid="preimage-key">{submitPreimage.data.slice(0, 18)}…</code>{" "}
                reads back:{" "}
                <span data-testid="preimage-content">
                  {preimage.data ? new TextDecoder().decode(preimage.data) : "looking up…"}
                </span>
              </span>
            )}
          </>
        ) : (
          <span className="muted" data-testid="preimage-unavailable">
            host only
          </span>
        )}
      </HookRow>
      {error && <p className="error">{error.message}</p>}
    </Card>
  );
}

// apps/example-vue/src/components/StoragePanel.vue
<script setup lang="ts">
import {
  useCid,
  useIsHost,
  usePreimage,
  useStorageAuthorization,
  useSubmitPreimage,
  useUpload,
} from "@use-truapi/vue";
import { computed, ref } from "vue";
import HookRow from "./HookRow.vue";
import UiCard from "./UiCard.vue";

const authorization = useStorageAuthorization();
const upload = useUpload();
const lastCid = ref<string | undefined>(undefined);
const fetched = useCid(() => lastCid.value);
const draft = ref("");
// Raw preimage path (host-only): submit bytes, read them back by key.
const isHost = useIsHost();
const submitPreimage = useSubmitPreimage();
const preimage = usePreimage(() => submitPreimage.data.value, { enabled: () => isHost.value });
const preimageText = computed(() =>
  preimage.data.value ? new TextDecoder().decode(preimage.data.value) : "looking up…",
);

const firstError = computed(
  () =>
    authorization.error.value ??
    upload.error.value ??
    fetched.error.value ??
    submitPreimage.error.value,
);

function onSubmitPreimage() {
  void submitPreimage.submit(new TextEncoder().encode(draft.value)).catch(() => {});
}

const fetchedText = computed(() =>
  fetched.data.value ? new TextDecoder().decode(fetched.data.value) : undefined,
);

function onUpload() {
  void upload
    .upload(new TextEncoder().encode(draft.value))
    .then((result) => {
      lastCid.value = result.cid?.toString();
    })
    .catch(() => {});
}
</script>

<template>
  <UiCard title="Cloud storage" desc="CID-addressed storage on the Bulletin chain.">
    <HookRow hook="useStorageAuthorization">
      <span class="badge" data-testid="storage-authorization">
        {{
          authorization.data.value
            ? authorization.data.value.authorized
              ? `quota: ${authorization.data.value.remainingTransactions} txns / ${authorization.data.value.remainingBytes} bytes`
              : "not authorized"
            : "checking quota…"
        }}
      </span>
    </HookRow>
    <HookRow hook="useUpload">
      <input data-testid="upload-input" v-model="draft" placeholder="Bytes to store" />
      <button
        type="button"
        data-testid="upload-submit"
        :disabled="upload.isPending.value || draft === ''"
        @click="onUpload"
      >
        {{ upload.isPending.value ? "Uploading…" : "Upload" }}
      </button>
    </HookRow>
    <HookRow hook="useCid">
      <span v-if="lastCid" class="muted">
        CID <code data-testid="upload-cid">{{ lastCid }}</code> reads back:
        <span data-testid="cid-content">{{ fetchedText ?? "fetching…" }}</span>
      </span>
      <span v-else class="muted">upload something to read it back by CID</span>
    </HookRow>
    <HookRow :hook="['useSubmitPreimage', 'usePreimage']">
      <template v-if="isHost">
        <button
          type="button"
          data-testid="preimage-submit"
          :disabled="submitPreimage.isPending.value || draft === ''"
          @click="onSubmitPreimage"
        >
          {{ submitPreimage.isPending.value ? "Submitting…" : "Submit as preimage" }}
        </button>
        <span v-if="submitPreimage.data.value" class="muted">
          key <code data-testid="preimage-key">{{ submitPreimage.data.value.slice(0, 18) }}…</code> reads back:
          <span data-testid="preimage-content">{{ preimageText }}</span>
        </span>
      </template>
      <span v-else class="muted" data-testid="preimage-unavailable">host only</span>
    </HookRow>
    <p v-if="firstError" class="error">{{ firstError.message }}</p>
  </UiCard>
</template>
